dathere/datapusher-plus

README.md
datapusher/main.py
setup.py

adapt datapusher_initdb command by @categulario

provide a datapusher_initdb command

---

README.md

nothing fancy, just two apt lines compacted into one and a repeated word in the readme

improvements to install instructions

---

README.md
datapusher/jobs.py
datapusher/settings.py

automatic dedup

---

Containerfile

To prevent a bug with deduplication of rows if set

Update Containerfile to use qsv 0.45.2

---

datapusher/jobs.py

In case of exception, qsv_validate does not exist.

Fix error handling in validate

---

datapusher/jobs.py

Use `--prefer-dmy` with `qsv` instead of `--prefer_dmy`

---

datapusher/config.py
datapusher/dot-env.template
datapusher/jobs.py

Add unsafe headers configuration settings

---

datapusher/jobs.py

if resource.format is just a file extension, we use it.
Otherwise, we try to get the file extension by guessing the mimetype
resolves #77

allow url parameters

---

datapusher/jobs.py

- rename generic url var to more specific resource_url
- use with statement to ensure connection is closed since we are streaming
- refine file format inferencing using content-type header
- also reorganized imports

Download improvements

---

ckanext/datapusher_plus/migration/datapusher_plus/README
ckanext/datapusher_plus/migration/datapusher_plus/alembic.ini
ckanext/datapusher_plus/migration/datapusher_plus/env.py
ckanext/datapusher_plus/migration/datapusher_plus/script.py.mako
ckanext/datapusher_plus/migration/datapusher_plus/versions/01_e9c4a88839c8_upgrade_jobs_table.py

Add migration script

---

Containerfile

Just that. I tried to run the container and it complained about requiring at least that version

upgrade container qsv to 0.118.0

---

datapusher/jobs.py

fixes #129
Thanks for the report @Zharktas !

Strip encoding result from `uchardet`

---

ckanext/datapusher_plus/config.py
ckanext/datapusher_plus/jobs.py
dot-env.template

Cherry-picking all the latest merges in the master

Sync with master

---

ckanext/datapusher_plus/jobs.py

Fix calling package action for resource

Fix calling package action for resource

---

README.md

Update README file for DP+ as extension

Update README file for DP+ as extension

---

ckanext/datapusher_plus/jobs.py

The same fix as in #160 but for dev-v1.0 branch.

Fix datefmt compatability with qsv in dev-v1.0

---

ckanext/datapusher_plus/plugin.py

Adding internal formats

---

README.md

After #160 and more changes I think we need to point QSV to 0.134

Update QSV refs

---

ckanext/datapusher_plus/logic/action.py
ckanext/datapusher_plus/utils.py

Fix the `api_token` config variable and fix for default views creation

Fix the api_token config variable and fix for default views creation

---

ckanext/datapusher_plus/migration/datapusher_plus/versions/03_23d45fa26447_add_job_key.py

Migration added

---

README.md

Update README with some fixes

---

ckanext/datapusher_plus/config.py
ckanext/datapusher_plus/jobs.py
ckanext/datapusher_plus/logging_utils.py
ckanext/datapusher_plus/plugin.py
ckanext/datapusher_plus/spatial_helpers.py

If a Shapefile is detected, unzips the shapefile and picks up the first .shp file it finds. Create a CSV from it and pushes it to the datastore.
Also added TRACE level so maintainers can see in detail it the process_spatial_file helper simplifies a shapefile.

feat: shapefile support

---

ckanext/datapusher_plus/datastore_utils.py
ckanext/datapusher_plus/jinja2_helpers.py
ckanext/datapusher_plus/jobs.py
ckanext/datapusher_plus/logging_utils.py
ckanext/datapusher_plus/qsv_utils.py

- make it more of an orchestrator and separate large codebase into separate logical modules
- cleanup imports
- add type hints and docstrings

Refactor jobs py

---

README.md
ckanext/datapusher_plus/datastore_utils.py
ckanext/datapusher_plus/jinja2_helpers.py

added formula helpers for compiling optional but recommended DCAT3 temporal properties that are typically hard to compile manually

DCAT 3 formula helpers

---

README.md
ckanext/datapusher_plus/config.py
ckanext/datapusher_plus/helpers.py
ckanext/datapusher_plus/jobs.py

auto unzip one file setting

---

README.md

Updates README text to say TxGIO instead of TNRIS along with changing the link.

docs: update TNRIS text to TxGIO along with link
