dathere/datapusher-plus

- README.md
- datapusher/main.py
- setup.py
Which was proposed to fix #249 
cc @categulario
> adapt initdb

- README.md
- deployment/datapusher.wsgi
ported from a PR to original `datapusher`. It allows setting the location of the settings file, which results quite useful for managing settings as a file but does not interfere with current settings from environment variables if `JOB_CONFIG` is not set.
> allow setting of the JOB_CONFIG variable

- Containerfile
- README.md
- container/initialize-and-start.sh
- container/uwsgi.ini
- datapusher/settings.py
Based on the one I mentioned in https://github.com/dathere/datapusher-plus/issues/8#issuecomment-1112786162 but adjusted to this repository.
I tested it in my own setup as a replacement and it works :)
it reads config values from the environment as specified in the readme.
> proposal of a Containerfile for datapusher-plus

- README.md
- datapusher/jobs.py
- input not only checks if a CSV file is well-formed per RFC4180, it transcodes to UTF-8, while being much smaller than the `validate` command.
> use `qsv input` instead of just `qsv validate`

- README.md
- datapusher/jobs.py
- datapusher/settings.py
> AUTO_ALIAS

- README.md
- datapusher/jobs.py
- datapusher/settings.py
only infer dates if one of the header names suggest a date as per #19
> smart date inferencing

- datapusher/config.py
MutableMapping must be imported like:
`from collections.abc import MutableMapping`
Imports of MutableMapping like
`from collections import MutableMapping`
have been deprecated since Python >=3.3 and will not work in Python >= 3.9
This explicit import from abc will prevent datapusher-plus from throwing errors or warnings and should be backwards compatible until Python 3.3
> fix import of MutableMapping from collections.abc

- Containerfile
- container/initialize-and-start.sh
- datapusher/main.py
- setup.py
Just updated datapusher-plus, and tried out using the Containerfile in the repo instead of sliding it into our own docker image. 
There were a few hurdles, mainly it looks like the Container file wasn't kept up to date. I will note that changing the import style (in https://github.com/dathere/datapusher-plus/commit/6c6dfec7dfd7068e08fd12b75fb3bfdcf6d91b02) might have some changes elsewhere. Normalizing this did fix the errors on datapusher_initdb.
It does still fail to initdb with sqllite, I think that's a permissions issue rather than anything fundamental. But since it's not really supported anymore, I didn't spend too much time on it.
> Container packaging fixes

- Containerfile
- Upgrade to ubuntu 22.04
- Install `file`, used to provide diagnostics when spreadsheets are not of the expected format
Fixes #75
> Containerfile dependencies

- datapusher/jobs.py
Can occur on a CSV with trailing empty headers:
`qsv headers -j` gives an output with trailing blank lines, and `strip()` removes them
> Don't crash on missing original column name

- ckanext/datapusher_plus/jobs.py
- ckanext/datapusher_plus/logic/action.py
- ckanext/datapusher_plus/utils.py
Fixes #72 
* Alternative callback URL for DataPusher when performing a request to CKAN
* remove redundant code
* fix typo
> [72]Rewrite resource url

- datapusher/jobs.py
`resource_name` isn't defined at one point before it's referenced, leading to a crash in certain instances. Fixed.
> caught a missing variable

- ckanext/datapusher_plus/cli.py
- ckanext/datapusher_plus/config.py
- ckanext/datapusher_plus/helpers.py
- ckanext/datapusher_plus/job_exceptions.py
- ckanext/datapusher_plus/jobs.py
- ckanext/datapusher_plus/model/__init__.py
- ckanext/datapusher_plus/model/jobs.py
- ckanext/datapusher_plus/plugin.py
- ckanext/datapusher_plus/utils.py
- dot-env.template
Create DB models for DP+ tables
Update jobs to use the correct tables
Add cli to create the tables into DB
> Feature db models

- datapusher/config.py
- datapusher/jobs.py
- datapusher/main.py
- datapusher/settings.py
- setup.py
Hi everyone, it's me again!
So I was trying to build and run the container for datapusher-plus and it failed in two ways:
* first it complained at run time about the import syntax for the internal `config` module from `main`. Indeed: `config` is not a globally registered module and therefore cannot be imported as `config` unless `$CWD` is `datapusher`, which I suspect most of the time is not. This PR fixes that. The fix assumes that this is installed as a python package, probably via `pip install -e` or similar, which is what the readme says anyways. I'm actually wondering how this worked to begin with.
* then it complained about some flask import that doesn't exist in the package flask-login. It turns out this is related to the release of flask 3 and it is fixed in `ckanserviceprovider` …
> import syntax and ckanserviceprovider version

- datapusher/dot-env.template
- datapusher/jobs.py
and since we don't want super big network packets, we reduce the default buffer size to 64k
> sync read buffer with buffer size of copyexpert

- datapusher/jobs.py
If file already is UTF-8 encoded, `qsv_input_utf_8_encoded_csv` file doesn't exist as it is created on `iconv` command.
> Fix input when file already is UTF-8

- ckanext/datapusher_plus/jobs.py
This PR implements a URL rewrite if the ckan_url differs from the start url of the CKAN resource URL, and the resource is an uploaded file. This might be useful for cases where CKAN is sitting behind a firewall or other authentication mechanism. It fixes #135
> Rewrite resource URL if it differs from the defined ckan_url

- datapusher/jobs.py
Alpine being a gift that keeps giving, musl iconv doesn't have output parameter at all, so this replaces it by using file descriptor.
> Fix using iconv on alpine

- ckanext/datapusher_plus/cli.py
- ckanext/datapusher_plus/plugin.py
This PR will be used to cleanup the CLI commands and move away from CKAN core datapusher code.
> Migrate cli commands

- ckanext/datapusher_plus/model/jobs.py
This PR fixes an issue with the new `init_tables()` method.
Running `meta.metadata.create_all(meta.engine)` will create the whole CKAN database among with all the tables that plugins add to the `Metadata` object. This creates problems when pipelining `datapusher-plus` database initialization with other plugins.
With this change, I'm only creating the 3 tables of this extension.
Note: I'm also applying some pep8 style fixes.
> [dev-v1.0] Fix init db command

- MANIFEST.in
Our config declaration has `*.yaml` extension, because of that it was not being copied properly when executing `pip install .`
This PR fixes the `MANIFEST.in` file to include `*.yaml` instead of `*.yml`
> Fix yaml extension in MANIFEST.in

- ckanext/datapusher_plus/templates/package/resource_edit_base.html
This will fix #158 .
`datapusher-plus:dev-v1.0` does no longer ship with webassets, so there is no need to call for them.
Let me know if you have other plans and I'm happy to create a new PR.
> Remove obsolete assets

- ckanext/datapusher_plus/jobs.py
- ckanext/datapusher_plus/logic/action.py
- ckanext/datapusher_plus/utils.py
It's not clear which token setting is required
This PR:
- Moves all references to the util `get_dp_plus_user_apitoken`
- Preserve the default `ckan.datapusher.api_token` and aldo continues using the new setting `ckan.datapusher_plus.api_token`
I'm not sure which one we expect to use.
Also:
- Small code changes to clean unused imports
> Ensure we are always using the same token setting for datapusher

- ckanext/datapusher_plus/config.py
- ckanext/datapusher_plus/config_declaration.yaml
- ckanext/datapusher_plus/jobs.py
- ckanext/datapusher_plus/spatial_helpers.py
Use logger properly and use its built-in ability to change log level rather than using a separate verbosity flag
> Refactor upload log level

- ckanext/datapusher_plus/config.py
- ckanext/datapusher_plus/helpers.py
- ckanext/datapusher_plus/jobs.py
- ckanext/datapusher_plus/plugin.py
- if a zip file contains only one file and that file is a supported format, DP+ goes ahead and processes the unzipped file and pushes it into the datastore
- if a zip file contains many files, it will extract the zip archive metadata for all the files and processes it as a CSV
Also: 
- cleaned up supported formats
- ensure "mean" column in stats is a TEXT, as it's not always a number (when doing mean for Dates)
- corrected default excel sheet to 0, as its a zero-based index
> feat: zip file support

- ckanext/datapusher_plus/config.py
- ckanext/datapusher_plus/jinja2_helpers.py
- ckanext/datapusher_plus/jobs.py
Infers which columns are lat/lon columns and set them in `dpp.LAT_FIELD` and `dpp.LON_FIELD` that can be accessed from Jinja2 formulae.
```
LATITUDE_FIELDS = tk.config.get(
"ckanext.datapusher_plus.latitude_fields",
"latitude,lat",
)
LONGITUDE_FIELDS = tk.config.get(
"ckanext.datapusher_plus.longitude_fields",
"longitude,lon",
)
```
> Lat lon columns inferencing for use in Formulas

- ckanext/datapusher_plus/jinja2_helpers.py
will use inferred lat/lon fields or spatial extent when available in the context
used pass_context decorator to automatically get context, instead of passing it manually
> "smart" formula spatial functions

- ckanext/datapusher_plus/datastore_utils.py
- ckanext/datapusher_plus/jinja2_helpers.py
- ckanext/datapusher_plus/jobs.py
- better registration of SQL-enabled Jinja2 formula helpers
- SQL-enabled Jinja2 formulas that work best with an index log a warning if no index is available
- move Formulae processing last, so Formulas that use SQL indices can take advantage of them if they are created in the Auto-Indexing phase
> refactored SQL-enabled formulas

- ckanext/datapusher_plus/jobs.py
at the end of DPP processing, the `package.dpp_suggestions.STATUS` is set to `DONE`
cc @minhajuddin2510
> refactor dpp_suggestions.STATUS to sync with Suggestions UI

- ckanext/datapusher_plus/jobs.py
To avoid situation where DP+ processing bails out early I have modified the way it checks for the existence of suggestion formula.
In the case where formulae exist and dpp_suggestions is in the schema but not the package, dpp_suggestions is added to the package and processing continues.
This is the logic ... 
- Check for suggestion formulae in package
- If exist, then
- Check for dpp_suggestions in schema
- If not exists
- bail out
- else
- Check for dpp_sugestions in package
- If not exists
- package_patch to add dpp_suggestions
- Else
- continue
- Else
- continue
> Improved dpp_suggestions check in jobs.py
